apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: sebsabi-dev
  # annotations:
  #   kubernetes.io/ingress.class: "nginx"
  #   cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - sebsabi.b.gebeyalearning.com
    secretName: frontend-tls-secret
  rules:
  - host: sebsabi.b.gebeyalearning.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80
