apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: betselot456/sebsabi-frontend:6048d4fce4ac436e8d063f44c50c06c9324fb3ba
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "http://api.sebsabi.gebeyalearning.com"
