apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: betselot456/sebsabi-frontend:0f0ee6060390777a1a7a35aa8b93680fe1ce9a83
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "https://api.sebsabi.b.gebeyalearning.com"
