apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
annotations:
  kubernetes.io/ingress.class: "nginx"
  cert-manager.io/issuer: "letsencrypt-prod"
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: betselot456/sebsabi-frontend:7bf8d20571cb851f09d0fc660fc566d327dbaee5
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "http://api.sebsabi.b.gebeyalearning.com"
