apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: betselot456/sebsabi-frontend:65d9eb7b2dd2e36ef2b67e8fed5996d9c32c20ec
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "http://api.sebsabi.b.gebeyalearning.com"
