apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: betselot456/sebsabi-frontend:57649dab48b62d758d0f609062a9ec689f429572
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "http://api.sebsabi.b.gebeyalearning.com"
