apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: betselot456/sebsabi-frontend:0fdaf2f13a4efaf56c06ba3d15f539770369ba84
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "https://api.sebsabi.b.gebeyalearning.com"
