apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: alazdev/identity-service:latest
        ports:
        - containerPort: 9595
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-core:5431/sebsabi_core
        - name: eureka.client.serviceUrl.defaultZone
          value: http://discovery-server:8761/eureka

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: identity-dep
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: identity-service
#   template:
#     metadata:
#       labels:
#         app: identity-service
#     spec:
#       containers:
#       - name: identity-service
#         image: alazdev/identity-service:latest
#         ports:
#         - containerPort: 9595
#         env: 
#         - name: DB_HOST
#           value: postgres-service
#         - name: DB_NAME
#           value: auth_service
#         - name: DB_PORT
#           value: '5432'
#         - name: DB_USERNAME
#           value: postgres
#         - name: DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: postgres-password-secret
#               key: postgres-password

