apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  # ports:
  #   - protocol: TCP
  #     port: 9595
  #     targetPort: 9595
  type: ClusterIP
