apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: betselot456/identity-service:0.0.1-SNAPSHOT-""
        ports:
        - containerPort: 9595
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-core:5432/sebsabi_core
        - name: eureka.client.serviceUrl.defaultZone
          value: http://discovery-server:8761/eureka
