apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: betselot456/auth-service:455babd141933fca63c05cee79ca825378a605de
        ports:
        - containerPort: 3005
        env: 
        - name: DB_HOST
          value: postgres-service
        - name: DB_NAME
          value: auth_service
        - name: DB_PORT
          value: '5432'
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password-secret
              key: postgres-password

