apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-sfs
spec:
  serviceName: postgres-core
  replicas: 1
  selector:
    matchLabels:
      app: postgres-core
  template:
    metadata:
      labels:
        app: postgres-core
    spec:
      containers:
      - name: postgres-core 
        image: "postgres:16"
        env:
        - name: POSTGRES_DB
          value: "sebsabi_core"
        - name: POSTGRES_USER
          value: "postgres"
        - name: PGDATA
          value: /data/postgres
        - name: POSTGRES_PASSWORD
          value: "1524"
          # valueFrom:
          #   secretKeyRef:
          #     name: postgres-password-secret
          #     key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-volume
          mountPath: /var/lib/postgresql/data      
          subPath: data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
