apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-sfs
spec:
  serviceName: postgres-core
  replicas: 1
  selector:
    matchLabels:
      app: postgres-core
  template:
    metadata:
      labels:
        app: postgres-core
    spec:
      containers:
      - name: postgres-core 
        image: "postgres:latest"
        env:
        - name: POSTGRES_DB
          value: "sebsabi_core"
        - name: POSTGRES_USER
          value: "alazar"
        - name: PGDATA
          value: /data/postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password-secret
              key: postgres-password
        ports:
        - containerPort: 5431
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
