apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-sfs
spec:
  serviceName: "postgresdb"
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: auth_service
        - name: POSTGRES_USER
          value: postgres
        - name: PGDATA
          value: /var/lib/postgreql/data
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password-secret
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: my-postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: my-postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
 