apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-dep
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: betselot456/service_discovery:0.0.1-SNAPSHOT-b898472
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: discovery-dep
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: service-discovery
#   template:
#     metadata:
#       labels:
#         app: service-discovery
#     spec:
#       containers:
#       - name: service-discovery
#         image: alazdev/service_discovery:latest
#         ports:
#         - containerPort: 8761
#         env: 
#         - name: DB_HOST
#           value: postgres-service
#         - name: DB_NAME
#           value: auth_service
#         - name: DB_PORT
#           value: '5432'
#         - name: DB_USERNAME
#           value: postgres
#         - name: DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: postgres-password-secret
#               key: postgres-password


