apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: discovery.sebsabi.b.gebeyalearning.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: discovery-server
            port:
              number: 8761