apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: betselot456/service_discovery:0.0.1-SNAPSHOT-$(git rev-parse --short HEAD)
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker


