apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: betselot456/notification-service:0.0.1-SNAPSHOT-b898472
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: eureka.client.serviceUrl.defaultZone
          value: http://discovery-server:8761/eureka
        - name: spring.kafka.bootstrap-servers
          value: broker:29092


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: identity-dep
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: identity-service
#   template:
#     metadata:
#       labels:
#         app: identity-service
#     spec:
#       containers:
#       - name: identity-service
#         image: alazdev/notification-service:latest
#         ports:
#         - containerPort: 9595
#         env: 
#         - name: DB_HOST
#           value: postgres-service
#         - name: DB_NAME
#           value: auth_service
#         - name: DB_PORT
#           value: '5432'
#         - name: DB_USERNAME
#           value: postgres
#         - name: DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: postgres-password-secret
#               key: postgres-password
