apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: betselot456/notification-service:0.0.1-SNAPSHOT-764b749
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: eureka.client.serviceUrl.defaultZone
          value: http://discovery-server:8761/eureka
        - name: spring.kafka.bootstrap-servers
          value: http://broker:29092
        - name: MAIL_HOST
          value: "smtp.gmail.com"
        - name: MAIL_PASS
          value: "diel epyv nozg yxvb" 
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_USER
          value: "sebsabiinc@gmail.com"
        
