apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core-service
        image: betselot456/sebsabi_core_service:0.0.1-SNAPSHOT-9719407
        ports:
        - containerPort: 9191
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-core:5432/sebsabi_core
        - name: eureka.client.serviceUrl.defaultZone
          value: http://discovery-server:8761/eureka
        - name: spring.kafka.bootstrap-servers
          value: broker:29092
